---
- name: Weather forecast
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure the airport code has been defined
      ansible.builtin.assert:
        that: "{{ airport_code is defined }}"
        fail_msg: Define the airport code ('-e airport_code=RDU')

    - name: Check the weather
      ansible.builtin.include_role:
        name: weather.demo.run
      vars:
        api_url: https://api.weather.gov/points/
        repo_url: https://github.com/ip2location/ip2location-iata-icao
